name: Create-Doc

on:
    issues:
        types: [opened, edited]
    push:
        branches: [main]

jobs:
    test:
        runs-on: windows-latest

        steps:
            - name: Pwd
              run: |
                pwd
                Invoke-WebRequest  http://bvets.net/archives/bvets6-msi.zip -o bve.zip
                ls

